=== julianladisch/mod-service-interaction/service/src/main/okapi/tenant/sample_data/generic_widget_definition_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Widget Definition",
  "type": "object",
  "description": "The generic shape a widget definition must contain",
  "additionalProperties": false,
  "required": ["type", "name", "version", "definition"],
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the WidgetDefinition, eg ERM Agreements SimpleSearch"
    },
    "version": {
      "type": "string",
      "description": "The version of this WidgetDefinition, of the form v1.0.0"
    },
    "type": { "$ref": "#/$defs/type" },
    "definition": { "$ref": "#/$defs/definition" }
  },
  "$defs": {
    "type": {
      "type": "object",
      "title": "Widget Definition Type",
      "description": "The WidgetType that this definition is created for",
      "additionalProperties": false,
      "required": ["name", "version"],
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the relevant WidgetType"
        },
        "version": {
          "type": "string",
          "description": "The version of the relevant WidgetType, of the form v1.0.0"
        }
      }
    },
    "definition": {
      "type": "object",
      "title": "Widget Definition",
      "description": "The actual JSON definition of an example widget for the specified type",
      "additionalProperties": true
    }
  }
}

=== julianladisch/mod-service-interaction/service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_licenses_simple_search_widget.json
{
  "type": {
    "name": "SimpleSearch",
    "version": "v1.0.0"
  },
  "version": "v1.0.0",
  "name":"ERM Licenses",
  "definition":{
    "baseUrl":"/licenses/licenses",
    "results": {
      "columns": [
        { 
          "name":"licenseName",
          "label": "License name",
          "accessPath":"name",
          "valueType": "String"
        },
        {
          "name":"startDate",
          "label": "Start date",
          "accessPath":"startDate",
          "valueType": "Date"
        },
        { 
          "name":"endDate",
          "label": "End date",
          "accessPath":"endDate",
          "valueType": "Date"
        },
        {
          "name":"openEnded",
          "label": "Open ended",
          "accessPath":"openEnded",
          "valueType": "Boolean"
        },
        {
          "name":"licenseStatus",
          "label": "Status",
          "accessPath":"status.value",
          "valueType": "String"
        },
        {
          "name":"licenseType",
          "label": "Type",
          "accessPath":"type.value",
          "valueType": "String"
        }
      ]
    },
    "filters": {
      "columns": [
        {
          "name":"licenseName",
          "label": "License name",
          "filterPath":"name",
          "valueType": "String",
          "comparators": ["==", "!="]
        },
        {
          "name":"licenseStatus",
          "label": "License status",
          "filterPath":"status.value",
          "valueType": "Enum",
          "enumValues": [
            {
              "value": "active",
              "label": "Active"
            },
            {
              "value": "in_negotiation",
              "label": "In negotiation"
            },
            {
              "value": "not_yet_active",
              "label": "Not yet active"
            },
            {
              "value": "rejected",
              "label": "Rejected"
            },
            {
              "value": "expired",
              "label": "Expired"
            }
          ],
          "comparators": ["==", "!="]
        },
        {
          "name":"licenseType",
          "label": "License type",
          "filterPath":"type.value",
          "valueType": "Enum",
          "enumValues": [
            {
              "value": "local",
              "label": "Local"
            },
            {
              "value": "consortial",
              "label": "Consortial"
            },
            {
              "value": "national",
              "label": "National"
            },
            {
              "value": "alliance",
              "label": "Alliance"
            }
          ],
          "comparators": ["==", "!="]
        },
        {
          "name":"startDate",
          "label": "Start date",
          "filterPath":"startDate",
          "valueType": "Date",
          "comparators": ["==", "!=", ">", ">=", "<", "<="]
        },
        {
          "name":"endDate",
          "label": "End date",
          "filterPath":"endDate",
          "valueType": "Date",
          "comparators": ["==", "!=", ">", ">=", "<", "<=", "isNull"]
        }
      ]
    },
    "sort": {
      "columns": [
        {
          "name":"id",
          "sortPath":"id",
          "sortTypes": ["asc"]
        },
        {
          "name":"licenseName",
          "sortPath":"name",
          "sortTypes": ["asc", "desc"]
        },
        {
          "name":"startDate",
          "sortPath":"startDate",
          "sortTypes": ["asc", "desc"]
        },
        {
          "name":"endDate",
          "sortPath":"endDate",
          "sortTypes": ["asc", "desc"]
        }
      ]
    },
    "configurableProperties": {
      "urlLink": {
        "configurable": true
      },
      "numberOfRows": {
        "configurable": true,
        "defValue": 5
      }
    }
  }
}
